export const APP_STATE_NOT_INITED = 'APP_STATE_NOT_INITED';
export const APP_STATE_INITIALIZATION = 'APP_STATE_INITIALIZATION';
export const APP_STATE_READY = 'APP_STATE_READY';

export const SOCKET_STATE_CONNECTED = 'SOCKET_STATE_CONNECTED';
export const SOCKET_STATE_CONNECTING = 'SOCKET_STATE_CONNECTING';
export const SOCKET_STATE_DISCONNECTED = 'SOCKET_STATE_DISCONNECTED';

export const MESSAGE_TYPE_REGISTER = 'REGISTER';
export const MESSAGE_TYPE_MESSAGE = 'MESSAGE';
export const MESSAGE_TYPE_INFO = 'INFO';
export const MESSAGE_TYPE_DENIED = 'DENIED';
export const MESSAGE_TYPE_USER_CONNECTED = 'USER_CONNECTED';
export const MESSAGE_TYPE_USER_DISCONNECTED = 'USER_DISCONNECTED';
export const MESSAGE_TYPE_USER_START_TYPING = 'START_TYPING';
export const MESSAGE_TYPE_USER_STOP_TYPING = 'STOP_TYPING';
export const MESSAGE_TYPE_USERS_LIST= 'USERS_LIST';
