export const APP_STATE_NOT_INITED = 'APP_STATE_NOT_INITED';
export const APP_STATE_INITIALIZATION = 'APP_STATE_INITIALIZATION';
export const APP_STATE_READY = 'APP_STATE_READY';

export const SOCKET_STATE_CONNECTED = 'SOCKET_STATE_CONNECTED';
export const SOCKET_STATE_CONNECTING = 'SOCKET_STATE_CONNECTING';
export const SOCKET_STATE_DISCONNECTED = 'SOCKET_STATE_DISCONNECTED';

export const MESSAGE_TYPE_REGISTER = 'REGISTER';
export const MESSAGE_TYPE_MESSAGE = 'MESSAGE';
export const MESSAGE_TYPE_INFO = 'INFO';
export const MESSAGE_TYPE_DENIED = 'DENIED';
