export const APP_STATE_NOT_INITED = 'APP_STATE_NOT_INITED';
export const APP_STATE_INITIALIZATION = 'APP_STATE_INITIALIZATION';
export const APP_STATE_READY = 'APP_STATE_READY';
export const APP_STATE_FAILED_INIT = 'APP_STATE_FAILED_INIT';

export const SOCKET_STATE_CONNECTED = 'SOCKET_STATE_CONNECTED';
export const SOCKET_STATE_CONNECTING = 'SOCKET_STATE_CONNECTING';
export const SOCKET_STATE_DISCONNECTED = 'SOCKET_STATE_DISCONNECTED';

export const C_MESSAGE_TYPE_REGISTER = 'REGISTER';
export const C_MESSAGE_TYPE_MESSAGE = 'MESSAGE';
export const C_MESSAGE_TYPE_GET_USER_LIST = 'GET_USER_LIST';
export const C_MESSAGE_TYPE_START_TYPING = 'START_TYPING';
export const C_MESSAGE_TYPE_STOP_TYPING = 'STOP_TYPING';

export const S_MESSAGE_TYPE_REGISTERED = 'REGISTERED';
export const S_MESSAGE_TYPE_DENIED = 'DENIED';
export const S_MESSAGE_TYPE_USER_LIST = 'USER_LIST';
export const S_MESSAGE_TYPE_USER_CONNECTED_BROADCAST = 'CONNECTED';
export const S_MESSAGE_TYPE_USER_DISCONNECTED_BROADCAST = 'DISCONNECTED';
export const S_MESSAGE_TYPE_MESSAGE_BROADCAST = 'MESSAGE';
export const S_MESSAGE_TYPE_START_TYPING_BROADCAST = 'START_TYPING';
export const S_MESSAGE_TYPE_STOP_TYPING_BROADCAST = 'STOP_TYPING';
