export const APP_INIT_START = 'APP_INIT_START';
export const APP_INIT_FAIL = 'APP_INIT_FAIL';
export const APP_INIT_OK = 'APP_INIT_OK';

export const SOCKET_INIT_CONNECTION = 'SOCKET_INIT_CONNECTION';
export const SOCKET_FAILED_TO_CONNECT = 'SOCKET_FAILED_TO_CONNECT';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_RECEIVE_MESSAGE = 'SOCKET_RECEIVE_MESSAGE';
export const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE';
export const SOCKET_ERROR = 'SOCKET_ERROR';

export const TEXT_TYPING_STOP_TIMEOUT = 'TEXT_TYPING_STOP_TIMEOUT';
